### PR TITLE
many additions to gtk and gdk packages

### PR DESCRIPTION
**Pull request by raichu**
These changes have been sitting in my private fork for a while.

BWT, I ran gofmt on gtk and gdk packages (per go community standards), maybe it's worth running gofmt on other packages and adding a git hook for it.

### CODE REVIEW

**Comment by raichu** [comment]
Another thing is, it appears that at some point the tree switched to Windows end-of-line, maybe it's worth running dos2unix on all files.

Also, it seems the original owners of gotk3 have [abandoned the project](https://github.com/conformal/gotk3/issues/112), so maybe you would like to enable the issue tracker in your repo?

**Comment by raichu** [comment]
Sorry for using the PR as an issue tracker, but there is another thing :)
Travis-CI is failing with "no environment variables set" (even in your current repo).

**Comment by andre-hub** [comment]
Thanks for your work and pull request.

Sorry, i forget the gofmt tool before i commited.

**Comment by raichu** [comment]
Thanks a lot for merging it!

**Pull request merged**
